#!/bin/bash
# Usage: iptables-flush [-6]

IPTABLES=/usr/sbin/iptables
TABLES="filter mangle raw"

if [[ "$1" == "-6" ]]; then
  IPTABLES=/usr/sbin/ip6tables
else
  # Only ipv4 has a nat table
  TABLES="$TABLES nat"
fi

for table in $TABLES; do
  $IPTABLES -t "$table" -F
  $IPTABLES -t "$table" -X
done

for chain in INPUT FORWARD OUTPUT; do
  $IPTABLES -P "$chain" ACCEPT
done

