#!/bin/sh

if ! [ -f /etc/ssh/ssh_host_key ]; then
  /usr/bin/ssh-keygen -t rsa1 -N "" -f /etc/ssh/ssh_host_key >/dev/null || exit 1
fi

if ! [ -f /etc/ssh/ssh_host_rsa_key ]; then
  /usr/bin/ssh-keygen -t rsa -N "" -f /etc/ssh/ssh_host_rsa_key >/dev/null || exit 1
fi

if ! [ -f /etc/ssh/ssh_host_dsa_key ]; then
  /usr/bin/ssh-keygen -t dsa -N "" -f /etc/ssh/ssh_host_dsa_key >/dev/null || exit 1
fi

# `test' returns non-zero when it fails. Don't let this hold up ExecStart.
exit 0
