#!/bin/sh

for ktype in rsa dsa ecdsa; do
  if ! [ -f /etc/ssh/ssh_host_${ktype}_key ]; then
    /usr/bin/ssh-keygen -t $ktype -N "" -f /etc/ssh/ssh_host_${ktype}_key >/dev/null || exit 1
  fi
done

# `test' returns non-zero when it fails. Don't let this hold up ExecStart.
exit 0
